In [1]:
import pandas as pd

In [2]:
df = pd.read_csv('assets/data.csv')

In [3]:
df.head()

        date  subscribers  reviews
0  2019/1/17         2671      194
1  2019/1/18         2671      195
2  2019/1/19         2674      197
3  2019/1/20         2685      199
4  2019/1/21         2695      199

In [6]:
type(df['date'][0])

str

In [7]:
import datetime

In [8]:

datetime.datetime.strptime(df['date'][0],'%Y/%m/%d').date()

datetime.date(2019, 1, 17)

In [11]:
dates=[]
for _date in df['date']:
    date= datetime.datetime.strptime(_date,'%Y/%m/%d').date()
    dates.append(date)

In [12]:
dates

[datetime.date(2019, 1, 17),
 datetime.date(2019, 1, 18),
 datetime.date(2019, 1, 19),
 datetime.date(2019, 1, 20),
 datetime.date(2019, 1, 21),
 datetime.date(2019, 1, 22),
 datetime.date(2019, 1, 23),
 datetime.date(2019, 1, 24),
 datetime.date(2019, 1, 25),
 datetime.date(2019, 1, 26),
 datetime.date(2019, 1, 27),
 datetime.date(2019, 1, 28),
 datetime.date(2019, 1, 29),
 datetime.date(2019, 1, 30),
 datetime.date(2019, 1, 31),
 datetime.date(2019, 2, 1),
 datetime.date(2019, 2, 2),
 datetime.date(2019, 2, 3),
 datetime.date(2019, 2, 4),
 datetime.date(2019, 2, 5),
 datetime.date(2019, 2, 6),
 datetime.date(2019, 2, 7),
 datetime.date(2019, 2, 8),
 datetime.date(2019, 2, 9),
 datetime.date(2019, 2, 10),
 datetime.date(2019, 2, 11),
 datetime.date(2019, 2, 12),
 datetime.date(2019, 2, 13),
 datetime.date(2019, 2, 14),
 datetime.date(2019, 2, 15),
 datetime.date(2019, 2, 16),
 datetime.date(2019, 2, 17),
 datetime.date(2019, 2, 18),
 datetime.date(2019, 2, 19),
 datetime.date(2019, 2, 20),
 datetime.date(2019, 2, 21),
 datetime.date(2019, 2, 22),
 datetime.date(2019, 2, 23),
 datetime.date(2019, 2, 24),
 datetime.date(2019, 2, 25),
 datetime.date(2019, 2, 26),
 datetime.date(2019, 2, 27),
 datetime.date(2019, 2, 28),
 datetime.date(2019, 3, 1),
 datetime.date(2019, 3, 2),
 datetime.date(2019, 3, 3),
 datetime.date(2019, 3, 4),
 datetime.date(2019, 3, 5),
 datetime.date(2019, 3, 6),
 datetime.date(2019, 3, 7),
 datetime.date(2019, 3, 8),
 datetime.date(2019, 3, 9),
 datetime.date(2019, 3, 10),
 datetime.date(2019, 3, 11),
 datetime.date(2019, 3, 12),
 datetime.date(2019, 3, 13),
 datetime.date(2019, 3, 14),
 datetime.date(2019, 3, 15),
 datetime.date(2019, 3, 16),
 datetime.date(2019, 3, 17),
 datetime.date(2019, 3, 18),
 datetime.date(2019, 3, 19),
 datetime.date(2019, 3, 20),
 datetime.date(2019, 3, 21),
 datetime.date(2019, 3, 22),
 datetime.date(2019, 3, 23),
 datetime.date(2019, 3, 24),
 datetime.date(2019, 3, 25),
 datetime.date(2019, 3, 26),
 datetime.date(2019, 3, 27),
 datetime.date(2019, 3, 28),
 datetime.date(2019, 3, 29),
 datetime.date(2019, 3, 30),
 datetime.date(2019, 3, 31),
 datetime.date(2019, 4, 1),
 datetime.date(2019, 4, 2),
 datetime.date(2019, 4, 3),
 datetime.date(2019, 4, 4),
 datetime.date(2019, 4, 5),
 datetime.date(2019, 4, 6),
 datetime.date(2019, 4, 7),
 datetime.date(2019, 4, 8),
 datetime.date(2019, 4, 9),
 datetime.date(2019, 4, 10),
 datetime.date(2019, 4, 11),
 datetime.date(2019, 4, 12),
 datetime.date(2019, 4, 13),
 datetime.date(2019, 4, 14),
 datetime.date(2019, 4, 15),
 datetime.date(2019, 4, 16),
 datetime.date(2019, 4, 17),
 datetime.date(2019, 4, 18),
 datetime.date(2019, 4, 19),
 datetime.date(2019, 4, 20),
 datetime.date(2019, 4, 21),
 datetime.date(2019, 4, 22),
 datetime.date(2019, 4, 23),
 datetime.date(2019, 4, 24),
 datetime.date(2019, 4, 25),
 datetime.date(2019, 4, 26),
 datetime.date(2019, 4, 27),
 datetime.date(2019, 4, 28),
 datetime.date(2019, 4, 29),
 datetime.date(2019, 4, 30),
 datetime.date(2019, 5, 1),
 datetime.date(2019, 5, 2),
 datetime.date(2019, 5, 3),
 datetime.date(2019, 5, 4),
 datetime.date(2019, 5, 5),
 datetime.date(2019, 5, 6),
 datetime.date(2019, 5, 7),
 datetime.date(2019, 5, 8),
 datetime.date(2019, 5, 9),
 datetime.date(2019, 5, 10),
 datetime.date(2019, 5, 11),
 datetime.date(2019, 5, 12),
 datetime.date(2019, 5, 13),
 datetime.date(2019, 5, 14),
 datetime.date(2019, 5, 15),
 datetime.date(2019, 5, 16),
 datetime.date(2019, 5, 17),
 datetime.date(2019, 5, 18),
 datetime.date(2019, 5, 19),
 datetime.date(2019, 5, 20),
 datetime.date(2019, 5, 21),
 datetime.date(2019, 5, 22),
 datetime.date(2019, 5, 23),
 datetime.date(2019, 5, 24),
 datetime.date(2019, 5, 25),
 datetime.date(2019, 5, 26),
 datetime.date(2019, 5, 27),
 datetime.date(2019, 5, 28),
 datetime.date(2019, 5, 29),
 datetime.date(2019, 5, 30),
 datetime.date(2019, 5, 31),
 datetime.date(2019, 6, 1),
 datetime.date(2019, 6, 2),
 datetime.date(2019, 6, 3),
 datetime.date(2019, 6, 4),
 datetime.date(2019, 6, 5),
 datetime.date(2019, 6, 6),
 datetime.date(2019, 6, 7),
 datetime.date(2019, 6, 8),
 datetime.date(2019, 6, 9),
 datetime.date(2019, 6, 10),
 datetime.date(2019, 6, 11),
 datetime.date(2019, 6, 12),
 datetime.date(2019, 6, 13),
 datetime.date(2019, 6, 14),
 datetime.date(2019, 6, 15),
 datetime.date(2019, 6, 16),
 datetime.date(2019, 6, 17),
 datetime.date(2019, 6, 18),
 datetime.date(2019, 6, 19),
 datetime.date(2019, 6, 20),
 datetime.date(2019, 6, 21),
 datetime.date(2019, 6, 22),
 datetime.date(2019, 6, 23),
 datetime.date(2019, 6, 24),
 datetime.date(2019, 6, 25),
 datetime.date(2019, 6, 26),
 datetime.date(2019, 6, 27),
 datetime.date(2019, 6, 28),
 datetime.date(2019, 6, 29),
 datetime.date(2019, 6, 30),
 datetime.date(2019, 7, 1),
 datetime.date(2019, 7, 2),
 datetime.date(2019, 7, 3),
 datetime.date(2019, 7, 4),
 datetime.date(2019, 7, 5),
 datetime.date(2019, 7, 6),
 datetime.date(2019, 7, 7),
 datetime.date(2019, 7, 8),
 datetime.date(2019, 7, 9),
 datetime.date(2019, 7, 10),
 datetime.date(2019, 7, 11),
 datetime.date(2019, 7, 12),
 datetime.date(2019, 7, 13),
 datetime.date(2019, 7, 14),
 datetime.date(2019, 7, 15),
 datetime.date(2019, 7, 16),
 datetime.date(2019, 7, 17),
 datetime.date(2019, 7, 18),
 datetime.date(2019, 7, 19),
 datetime.date(2019, 7, 20),
 datetime.date(2019, 7, 21),
 datetime.date(2019, 7, 22),
 datetime.date(2019, 7, 23),
 datetime.date(2019, 7, 24),
 datetime.date(2019, 7, 25),
 datetime.date(2019, 7, 26),
 datetime.date(2019, 7, 27),
 datetime.date(2019, 7, 28),
 datetime.date(2019, 7, 29),
 datetime.date(2019, 7, 30),
 datetime.date(2019, 7, 31),
 datetime.date(2019, 8, 1),
 datetime.date(2019, 8, 2),
 datetime.date(2019, 8, 3),
 datetime.date(2019, 8, 4),
 datetime.date(2019, 8, 5),
 datetime.date(2019, 8, 6),
 datetime.date(2019, 8, 7),
 datetime.date(2019, 8, 8),
 datetime.date(2019, 8, 9),
 datetime.date(2019, 8, 10),
 datetime.date(2019, 8, 11),
 datetime.date(2019, 8, 12),
 datetime.date(2019, 8, 13),
 datetime.date(2019, 8, 14),
 datetime.date(2019, 8, 15),
 datetime.date(2019, 8, 16),
 datetime.date(2019, 8, 17),
 datetime.date(2019, 8, 18),
 datetime.date(2019, 8, 19),
 datetime.date(2019, 8, 20),
 datetime.date(2019, 8, 21),
 datetime.date(2019, 8, 22),
 datetime.date(2019, 8, 23),
 datetime.date(2019, 8, 24),
 datetime.date(2019, 8, 25),
 datetime.date(2019, 8, 26),
 datetime.date(2019, 8, 27),
 datetime.date(2019, 8, 28),
 datetime.date(2019, 8, 29),
 datetime.date(2019, 8, 30),
 datetime.date(2019, 8, 31),
 datetime.date(2019, 9, 1),
 datetime.date(2019, 9, 2),
 datetime.date(2019, 9, 3),
 datetime.date(2019, 9, 4),
 datetime.date(2019, 9, 5),
 datetime.date(2019, 9, 6),
 datetime.date(2019, 9, 7),
 datetime.date(2019, 9, 8),
 datetime.date(2019, 9, 9),
 datetime.date(2019, 9, 10),
 datetime.date(2019, 9, 11),
 datetime.date(2019, 9, 12),
 datetime.date(2019, 9, 13),
 datetime.date(2019, 9, 14),
 datetime.date(2019, 9, 15),
 datetime.date(2019, 9, 16),
 datetime.date(2019, 9, 17),
 datetime.date(2019, 9, 18),
 datetime.date(2019, 9, 19),
 datetime.date(2019, 9, 20),
 datetime.date(2019, 9, 21),
 datetime.date(2019, 9, 22),
 datetime.date(2019, 9, 23),
 datetime.date(2019, 9, 24),
 datetime.date(2019, 9, 25),
 datetime.date(2019, 9, 26),
 datetime.date(2019, 9, 27),
 datetime.date(2019, 9, 28),
 datetime.date(2019, 9, 29),
 datetime.date(2019, 9, 30),
 datetime.date(2019, 10, 1),
 datetime.date(2019, 10, 2),
 datetime.date(2019, 10, 3),
 datetime.date(2019, 10, 4),
 datetime.date(2019, 10, 5),
 datetime.date(2019, 10, 6),
 datetime.date(2019, 10, 7),
 datetime.date(2019, 10, 8),
 datetime.date(2019, 10, 9),
 datetime.date(2019, 10, 10),
 datetime.date(2019, 10, 11),
 datetime.date(2019, 10, 12),
 datetime.date(2019, 10, 13),
 datetime.date(2019, 10, 14),
 datetime.date(2019, 10, 15),
 datetime.date(2019, 10, 16),
 datetime.date(2019, 10, 17),
 datetime.date(2019, 10, 18),
 datetime.date(2019, 10, 19),
 datetime.date(2019, 10, 20),
 datetime.date(2019, 10, 21),
 datetime.date(2019, 10, 22),
 datetime.date(2019, 10, 23),
 datetime.date(2019, 10, 24)]

In [15]:
n_subscribers = df['subscribers'].values
n_subscribers

array([2671, 2671, 2674, 2685, 2695, 2701, 2710, 2718, 2722, 2725, 2734,
       2753, 2773, 2785, 2803, 2845, 2847, 2847, 2851, 2852, 2857, 2861,
       2865, 2870, 2875, 2892, 2906, 2919, 2942, 2974, 2977, 2978, 2981,
       2983, 2984, 2987, 2989, 2993, 2995, 3009, 3014, 3023, 3031, 3052,
       3060, 3062, 3063, 3066, 3071, 3074, 3076, 3077, 3080, 3087, 3089,
       3093, 3098, 3104, 3112, 3120, 3131, 3142, 3162, 3173, 3180, 3187,
       3189, 3196, 3212, 3220, 3226, 3241, 3253, 3255, 3258, 3262, 3264,
       3272, 3275, 3276, 3279, 3285, 3300, 3306, 3312, 3319, 3324, 3325,
       3329, 3331, 3332, 3333, 3336, 3339, 3343, 3349, 3357, 3370, 3388,
       3412, 3437, 3439, 3440, 3447, 3466, 3481, 3504, 3522, 3527, 3533,
       3543, 3546, 3555, 3566, 3583, 3594, 3614, 3633, 3647, 3648, 3649,
       3651, 3654, 3658, 3671, 3675, 3681, 3694, 3699, 3711, 3722, 3734,
       3766, 3781, 3784, 3789, 3790, 3793, 3795, 3808, 3830, 3843, 3857,
       3870, 3895, 3919, 3942, 3983, 4022, 4053, 4058, 4063, 4064, 4065,
       4066, 4069, 4070, 4073, 4084, 4108, 4122, 4132, 4150, 4162, 4164,
       4167, 4174, 4179, 4187, 4200, 4210, 4211, 4214, 4219, 4223, 4228,
       4236, 4239, 4243, 4250, 4265, 4288, 4313, 4329, 4329, 4329, 4333,
       4335, 4353, 4370, 4397, 4419, 4422, 4423, 4425, 4427, 4432, 4433,
       4435, 4437, 4440, 4444, 4452, 4466, 4493, 4521, 4528, 4529, 4532,
       4534, 4535, 4539, 4539, 4541, 4545, 4545, 4561, 4590, 4624, 4641,
       4665, 4702, 4730, 4761, 4793, 4846, 4878, 4884, 4888, 4887, 4888,
       4890, 4892, 4894, 4896, 4907, 4918, 4935, 4949, 4965, 4966, 4966,
       4970, 4972, 4974, 4996, 4998, 5001, 5004, 5005, 5012, 5023, 5033,
       5068, 5084, 5088, 5097, 5113, 5117, 5120, 5128, 5133, 5137, 5144,
       5160, 5166, 5167, 5168, 5169, 5170, 5170, 5179, 5185, 5187, 5189,
       5191, 5193, 5194, 5197, 5210, 5229], dtype=int64)

In [16]:
n_reviews =  df['reviews'].values
n_reviews

array([194, 195, 197, 199, 199, 200, 200, 201, 201, 201, 202, 204, 206,
       208, 210, 211, 213, 213, 217, 218, 219, 220, 222, 224, 224, 227,
       229, 229, 231, 232, 234, 234, 234, 234, 237, 239, 239, 241, 241,
       241, 243, 243, 243, 244, 245, 246, 249, 252, 254, 255, 256, 258,
       258, 261, 261, 262, 262, 262, 262, 262, 265, 266, 266, 268, 269,
       271, 271, 274, 274, 274, 275, 275, 278, 278, 280, 282, 282, 282,
       284, 287, 289, 289, 291, 293, 295, 295, 295, 297, 298, 299, 299,
       299, 299, 299, 300, 302, 303, 303, 304, 304, 305, 305, 308, 309,
       310, 311, 314, 317, 322, 324, 327, 328, 330, 332, 334, 335, 338,
       340, 344, 349, 349, 351, 351, 354, 354, 359, 359, 361, 361, 364,
       368, 373, 374, 375, 375, 378, 379, 380, 383, 385, 386, 387, 390,
       394, 395, 397, 399, 402, 404, 409, 410, 414, 417, 422, 424, 425,
       426, 427, 427, 427, 433, 436, 440, 440, 446, 448, 450, 455, 456,
       456, 458, 458, 464, 464, 468, 469, 469, 471, 471, 473, 476, 476,
       483, 483, 486, 487, 492, 493, 494, 496, 500, 504, 507, 513, 516,
       518, 519, 520, 522, 522, 526, 528, 528, 529, 529, 530, 531, 533,
       534, 537, 537, 539, 540, 541, 544, 545, 548, 549, 549, 552, 554,
       557, 561, 564, 566, 566, 571, 572, 573, 574, 575, 577, 577, 578,
       578, 579, 581, 583, 583, 584, 587, 587, 590, 590, 592, 596, 601,
       601, 603, 605, 605, 609, 609, 612, 613, 614, 615, 617, 618, 620,
       622, 624, 628, 630, 633, 637, 639, 641, 644, 646, 649, 651, 651,
       652, 653, 654, 655, 656, 658, 659, 663], dtype=int64)

In [18]:
diff_subscribers = df['subscribers'].diff().values

In [19]:
diff_subscribers

array([nan,  0.,  3., 11., 10.,  6.,  9.,  8.,  4.,  3.,  9., 19., 20.,
       12., 18., 42.,  2.,  0.,  4.,  1.,  5.,  4.,  4.,  5.,  5., 17.,
       14., 13., 23., 32.,  3.,  1.,  3.,  2.,  1.,  3.,  2.,  4.,  2.,
       14.,  5.,  9.,  8., 21.,  8.,  2.,  1.,  3.,  5.,  3.,  2.,  1.,
        3.,  7.,  2.,  4.,  5.,  6.,  8.,  8., 11., 11., 20., 11.,  7.,
        7.,  2.,  7., 16.,  8.,  6., 15., 12.,  2.,  3.,  4.,  2.,  8.,
        3.,  1.,  3.,  6., 15.,  6.,  6.,  7.,  5.,  1.,  4.,  2.,  1.,
        1.,  3.,  3.,  4.,  6.,  8., 13., 18., 24., 25.,  2.,  1.,  7.,
       19., 15., 23., 18.,  5.,  6., 10.,  3.,  9., 11., 17., 11., 20.,
       19., 14.,  1.,  1.,  2.,  3.,  4., 13.,  4.,  6., 13.,  5., 12.,
       11., 12., 32., 15.,  3.,  5.,  1.,  3.,  2., 13., 22., 13., 14.,
       13., 25., 24., 23., 41., 39., 31.,  5.,  5.,  1.,  1.,  1.,  3.,
        1.,  3., 11., 24., 14., 10., 18., 12.,  2.,  3.,  7.,  5.,  8.,
       13., 10.,  1.,  3.,  5.,  4.,  5.,  8.,  3.,  4.,  7., 15., 23.,
       25., 16.,  0.,  0.,  4.,  2., 18., 17., 27., 22.,  3.,  1.,  2.,
        2.,  5.,  1.,  2.,  2.,  3.,  4.,  8., 14., 27., 28.,  7.,  1.,
        3.,  2.,  1.,  4.,  0.,  2.,  4.,  0., 16., 29., 34., 17., 24.,
       37., 28., 31., 32., 53., 32.,  6.,  4., -1.,  1.,  2.,  2.,  2.,
        2., 11., 11., 17., 14., 16.,  1.,  0.,  4.,  2.,  2., 22.,  2.,
        3.,  3.,  1.,  7., 11., 10., 35., 16.,  4.,  9., 16.,  4.,  3.,
        8.,  5.,  4.,  7., 16.,  6.,  1.,  1.,  1.,  1.,  0.,  9.,  6.,
        2.,  2.,  2.,  2.,  1.,  3., 13., 19.])

In [20]:
diff_reviews = df['reviews'].diff().values
diff_reviews

array([nan,  1.,  2.,  2.,  0.,  1.,  0.,  1.,  0.,  0.,  1.,  2.,  2.,
        2.,  2.,  1.,  2.,  0.,  4.,  1.,  1.,  1.,  2.,  2.,  0.,  3.,
        2.,  0.,  2.,  1.,  2.,  0.,  0.,  0.,  3.,  2.,  0.,  2.,  0.,
        0.,  2.,  0.,  0.,  1.,  1.,  1.,  3.,  3.,  2.,  1.,  1.,  2.,
        0.,  3.,  0.,  1.,  0.,  0.,  0.,  0.,  3.,  1.,  0.,  2.,  1.,
        2.,  0.,  3.,  0.,  0.,  1.,  0.,  3.,  0.,  2.,  2.,  0.,  0.,
        2.,  3.,  2.,  0.,  2.,  2.,  2.,  0.,  0.,  2.,  1.,  1.,  0.,
        0.,  0.,  0.,  1.,  2.,  1.,  0.,  1.,  0.,  1.,  0.,  3.,  1.,
        1.,  1.,  3.,  3.,  5.,  2.,  3.,  1.,  2.,  2.,  2.,  1.,  3.,
        2.,  4.,  5.,  0.,  2.,  0.,  3.,  0.,  5.,  0.,  2.,  0.,  3.,
        4.,  5.,  1.,  1.,  0.,  3.,  1.,  1.,  3.,  2.,  1.,  1.,  3.,
        4.,  1.,  2.,  2.,  3.,  2.,  5.,  1.,  4.,  3.,  5.,  2.,  1.,
        1.,  1.,  0.,  0.,  6.,  3.,  4.,  0.,  6.,  2.,  2.,  5.,  1.,
        0.,  2.,  0.,  6.,  0.,  4.,  1.,  0.,  2.,  0.,  2.,  3.,  0.,
        7.,  0.,  3.,  1.,  5.,  1.,  1.,  2.,  4.,  4.,  3.,  6.,  3.,
        2.,  1.,  1.,  2.,  0.,  4.,  2.,  0.,  1.,  0.,  1.,  1.,  2.,
        1.,  3.,  0.,  2.,  1.,  1.,  3.,  1.,  3.,  1.,  0.,  3.,  2.,
        3.,  4.,  3.,  2.,  0.,  5.,  1.,  1.,  1.,  1.,  2.,  0.,  1.,
        0.,  1.,  2.,  2.,  0.,  1.,  3.,  0.,  3.,  0.,  2.,  4.,  5.,
        0.,  2.,  2.,  0.,  4.,  0.,  3.,  1.,  1.,  1.,  2.,  1.,  2.,
        2.,  2.,  4.,  2.,  3.,  4.,  2.,  2.,  3.,  2.,  3.,  2.,  0.,
        1.,  1.,  1.,  1.,  1.,  2.,  1.,  4.])

In [21]:
df = pd.read_csv('assets/data.csv')
dates=[]
for _date in df['date']:
    date= datetime.datetime.strptime(_date,'%Y/%m/%d').date()
    dates.append(date)
    
n_subscribers = df['subscribers'].values
n_reviews =  df['reviews'].values

diff_subscribers = df['subscribers'].diff().values
diff_reviews = df['reviews'].diff().values